"""fase_1b_auth_licencias_permisos

Revision ID: b50a547b7c7e
Revises: aa492d082e73
Create Date: 2026-03-11 18:42:29.368551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50a547b7c7e'
down_revision: Union[str, None] = 'aa492d082e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modules_allowed', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permission_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_company_licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('license_type_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['license_type_id'], ['license_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tenant_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', 'license_type_id', name='uq_user_company_license')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('permission_object_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('set_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['permission_object_id'], ['permission_objects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tenant_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', 'permission_object_id', name='uq_user_company_permission')
    )
    op.add_column('subscription_plans', sa.Column('quota_professional', sa.Integer(), nullable=False))
    op.add_column('subscription_plans', sa.Column('quota_logistics', sa.Integer(), nullable=False))
    op.add_column('subscription_plans', sa.Column('quota_finance', sa.Integer(), nullable=False))
    op.add_column('subscription_plans', sa.Column('quota_crm', sa.Integer(), nullable=False))
    op.add_column('tenant_users', sa.Column('hashed_password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_users', 'hashed_password')
    op.drop_column('subscription_plans', 'quota_crm')
    op.drop_column('subscription_plans', 'quota_finance')
    op.drop_column('subscription_plans', 'quota_logistics')
    op.drop_column('subscription_plans', 'quota_professional')
    op.drop_table('user_permissions')
    op.drop_table('user_company_licenses')
    op.drop_table('permission_objects')
    op.drop_table('license_types')
    # ### end Alembic commands ###
